/*
 * Generated by ./misc/optlib2c from optlib/objdumpd.ctags, Don't edit this manually.
 */
#include "general.h"
#include "parse.h"
#include "routines.h"
#include "field.h"
#include "xtag.h"


static void initializeObjdumpDParser (const langType language CTAGS_ATTR_UNUSED)
{
}

extern parserDefinition* ObjdumpDParser (void)
{
	static const char *const extensions [] = {
		"objdump",
		NULL
	};

	static const char *const aliases [] = {
		NULL
	};

	static const char *const patterns [] = {
		NULL
	};

	static roleDefinition ObjdumpDSymbolRoleTable [] = {
		{
		  true, "called", "specified as a callable",
		},
	};
	static kindDefinition ObjdumpDKindTable [] = {
		{
		  true, 'S', "section", "sections",
		},
		{
		  true, 's', "symbol", "symbols",
		  ATTACH_ROLES(ObjdumpDSymbolRoleTable),
		},
	};
	static tagRegexTable ObjdumpDTagRegexTable [] = {
		{"^Disassembly of section ([^:]+)", "\\1",
		"S", "p{exclusive}"
		"{{\n"
		"   _scopeclear\n"
		"   .  _scopepush\n"
		"}}", NULL, false},
		{"^[0-9a-f]+ <([^>]+)>:", "\\1",
		"s", "p{exclusive}"
		"{{\n"
		"   _scopedepth 2 eq {\n"
		"      _scopepop\n"
		"   } if\n"
		"   . _scoperef\n"
		"   . _scopepush\n"
		"}}", NULL, false},
		{"^[ \t]+[0-9a-f]+:[ \t]+(?:(?:[0-9a-f][0-9a-f] )+|[0-9a-f]+)[ \t]+(?:call.+|bl)[^<]*<([^>+]+)(\\+0x[a-f0-9]+)?>.*", "\\1",
		"s", "p{_role=called}"
		"{{\n"
		"   _scopetop {\n"
		"      . _scoperef\n"
		"      :name . :name eq {\n"
		"         . _markplaceholder\n"
		"      } if\n"
		"   } if\n"
		"}}", NULL, false},
	};


	parserDefinition* const def = parserNew ("ObjdumpD");

	def->versionCurrent= 0;
	def->versionAge    = 0;
	def->enabled       = true;
	def->extensions    = extensions;
	def->patterns      = patterns;
	def->aliases       = aliases;
	def->method        = METHOD_NOT_CRAFTED|METHOD_REGEX;
	def->useCork       = CORK_QUEUE;
	def->kindTable     = ObjdumpDKindTable;
	def->kindCount     = ARRAY_SIZE(ObjdumpDKindTable);
	def->tagRegexTable = ObjdumpDTagRegexTable;
	def->tagRegexCount = ARRAY_SIZE(ObjdumpDTagRegexTable);
	def->initialize    = initializeObjdumpDParser;

	return def;
}
